version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  scoober-1:
    image: scoober-1:latest
#    user: root
#    volumes:
#      - /scripts/foo.sh:/c/foo.sh
    build:
      dockerfile: Dockerfile
      context: .
    container_name: scoober-1
    #    command: sh -c "./foo.sh"
    ports:
      - "8080:8080"
    depends_on:
      - redis
#    entrypoint: [ "sh","-c","/c/foo.sh" ]
  scoober-2:
    image: scoober-2:latest
#    user: root
#    volumes:
#      - /scripts/foo.sh:/c/foo.sh
    build:
      dockerfile: Dockerfile
      context: .
    container_name: scoober-2
    #    command: sh -c "./foo.sh"
    ports:
      - "9090:9090"
    depends_on:
      - redis
#    entrypoint: [ "sh","-c","/c/foo.sh" ]